### ISSUE TITLE
SwrveSDKCommon/SwrvePush.h file not found

### ISSUE THREAD

**Issue by jorge-lopez-alarcon** [Swrve/swrve-cordova-sdk#13]
After adding the ios platform and performing the prepare, the project is opened in xcode and the build process shows the error 'SwrveSDKCommon/SwrvePush.h file not found'

cordova-ios: ^6.2.0

ionic info
![image](https://user-images.githubusercontent.com/6467495/155366258-91204e08-cce1-46e7-af94-4b19f1818026.png)

**Comment by adam-govan** [comment]
Hello @RTX-3090 , Thank you for bringing this to our attention, we'll investigate this issue.

We have noticed if you have an application with spaces in it's name the **framework search paths** in **build settings** of the extension get slightly thrown off and the pathing doesn't work. As a workaround, you can add quotes around the path inside Xcode. for example: 

An application with the name: `My Application` would show up in the framework search paths as: 
```
my application/Plugins/cordova-plugin-swrve
```

but but that actually puts a newline between `my` and `application`. So if you wanted to get around this build issue quickly you can either update the application name to have no spaces or you can add quotes around in xcode like so: 

```
"my application/Plugins/cordova-plugin-swrve"
```

If you don't have any spaces in your application name please let us know as this has been the only way we can reproduce this issue on our end. 

Thank you!

**Comment by jorge-lopez-alarcon** [comment]
> Hello @RTX-3090 , Thank you for bringing this to our attention, we'll investigate this issue.
> 
> We have noticed if you have an application with spaces in it's name the **framework search paths** in **build settings** of the extension get slightly thrown off and the pathing doesn't work. As a workaround, you can add quotes around the path inside Xcode. for example:
> 
> An application with the name: `My Application` would show up in the framework search paths as:
> 
> ```
> my application/Plugins/cordova-plugin-swrve
> ```
> 
> but but that actually puts a newline between `my` and `application`. So if you wanted to get around this build issue quickly you can either update the application name to have no spaces or you can add quotes around in xcode like so:
> 
> ```
> "my application/Plugins/cordova-plugin-swrve"
> ```
> 
> If you don't have any spaces in your application name please let us know as this has been the only way we can reproduce this issue on our end.
> 
> Thank you!

Hi @adam-govan , thanks for replying.
I found this line in the plugin, some suggestion of how it should be for projects that have space in the name

Thank you!

![image](https://user-images.githubusercontent.com/6467495/155551100-e2b8dfb6-b068-47db-a142-012741719d3a.png)

![image](https://user-images.githubusercontent.com/6467495/155551633-274fcb65-daa7-4084-8c96-0e23426e3ff7.png)

**Comment by adam-govan** [comment]
hi @RTX-3090 great find! I'll be sure to apply the quotes around `swrveSDKCommonDirectory` to our next release. 
Thank you!

**Comment by adam-govan** [comment]
Sorry, I forgot to ask. Did that resolve your pathfinding issue in the end?

**Comment by jorge-lopez-alarcon** [comment]
> Sorry, I forgot to ask. Did that resolve your pathfinding issue in the end?

Hi @adam-govan the solution works perfectly by editing the path in xcode, but I want to make the change in the plugin to avoid that manual process.

I will try with this change
![image](https://user-images.githubusercontent.com/6467495/155566935-cc46d2b6-611e-40b2-9f71-a648fabb2761.png)

**Comment by adam-govan** [comment]
Great! then i'll raise a ticket to update our plugin with a similar change and close this issue for now

Thank you!
